image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
 -  mkdir -p ~/.docker/cli-plugins/
  - curl -L https://github.com/docker/compose-cli/releases/download/v2.0.0-rc.1/docker-compose-linux-amd64 -o ~/.docker/cli-plugins/docker-compose
  - chmod +x ~/.docker/cli-plugins/docker-compose
  - sudo docker-compose up -d
  - sleep 15
  - java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -jar artifacts/aqa-shop.jar &
  - sleep 15

build_script:
  - chmod +x gradlew
  - ./gradlew  test -Ddb.url=jdbc:mysql://localhost:3306/app --info "-Dselenideheadless=true"
